POST http://localhost:8084/api/v1/transaction/sendSMStoClient
Content-Type: application/json

{
  "recipient": "212605809656",
  "message": "This is a sample message",
  "sender" : "Ismail"
}
###


POST http://localhost:8083/TRANSFERSERVICE/api/v1/transaction/agent/SubmitTransaction
Content-Type: application/json

{
  "donorId": "1",
  "beneficiaryId": "2",
  "amount": 1,
  "whoPayFees": "donor",
  "isNotificationFees": true,
  "notify": true,
  "fraisTransfert": 2
}